version: '3'
services:
  
  web-vue:
    hostname: web-vue
    build: .
    environment:
      process.env.VUE_APP_RUTA_API: "http://0.0.0.0:4000"
      
    links:
      - "mydb:json-server"  
    command: npm run serve
    ports:
      - "8087:8087"
    depends_on:
      - mydb
    networks:
      conexion_networks:
        aliases:
          - conexion_bd
          
         
  mydb:
    hostname: mydb
    build: . 
    command: Set-ExecutionPolicy -Scope CurrentUser unrestricted
    command: json-server -H 0.0.0.0 -p 4000 --watch database/db.json
    ports:
      - "4000:4000"
    networks:
     conexion_networks:
       aliases:
        - conexion2_bd
     
networks:
   conexion_networks:
     name: conexion_net
     driver: bridge
     ipam:
       driver: default
